FROM node:18-alpine

WORKDIR /app

# Copia los archivos de dependencias reales
COPY package.json package-lock.json ./

# Instala dependencias
RUN npm install

# Copia el resto del código
COPY . .

EXPOSE 3002

CMD ["npm", "run", "dev"]
